#Name: Jahin Zaman
# Version 1 Date: 5/24/2021 
# Version 2 date 5/25/2021 - Peer reviewed Ornib, and technically teacher feedback
#Version 3 date 5/27/2021 - Peer Reviewed Ornib
#Teacher Feedback Changes(Teacher didn't really give me feedback but I just used the feedback he gave to another student on sounds as feedback): Adding sounds and how to add sounds.
#Instructions:
#PRESS I FOR ACTUAL INSTRUCTIONS WHEN YOU RUN THE GAME(make sure to open up the instructions first)
#Rubric Requirements/Locations
#Requirements:
#Code Organization - Perfect
#Functions - line 147 - detailed function in correct format, line 165, detailed function in correct format
#,line 175, detailed function in correct format, 183 - detailed function in correct format
#Objects: All Shapes ARE given variable names as seen line lines 34-43 and many other lines
#Lists is shown on line 104, Instruction; 
#Groups on lines 96-110, angelDevil and empty groups that get items through for loops later
#Events - onMousePress() on line 200, onKeyPress() on Line 334, onKeyHold on line 352
#Complex Conditionals - and Used on line 287, 3 times, in function onStep() and if statement, and
# used in line 307 in onStep() in if statement() and line 320
#Properties and Methods - used all throughout lines 118-149
#Loops - Line 160, ranged loop, Line 184, ranged loop, Line 186, Nested Ranged Loop, Line 297, group.children loop,
# Line 343 - Looping over a list
#Shape Groups - Shapes ARE organized into groups as recognizable objects
# Motion - automatic motion with onStep(), line 290,  and manual motion with onKeyHold() in line 359
#Debugged - Yes it works without error 
#Instructions - Press I for instructions which is clearly stated when you press run and X to close the instructions
#Navigation - Navigation is easy, all you have to do is click the mouse and press some buttons 
# and as long as you read the instructions everything SHOULD be alright
# Intuitive - Play feels right and is hard(very)
# Professional - All the tests and sounds are school friendly(no nsfw), but THERE MAY BE A JUMPSCARE HAHAHA!!!!


#NOTE: THESE COMMENTS MAY HAVE CHANGED THE POSITIONS OF THE LINES MENTIOEND IN THE COMMENTS


#Constants
app.background='lightBlue'
#Sets the Background
app.stepsPerSecond=30
#Sets the stepsPerSecond
#Global Variables:
app.timer=0
#Creates a timer that will be used for the image and sound later on
app.score = 0
#Creates a score variable that increases as you destroy objects.
app.isAngel = None
#Creates a boolean that will be used to switch between the angel and devil through an if condition
app.manualPilot = False
#Creates a boolean that will be used to switch from automatic movement to manual movement during keyPress
app.counter=0
#Counter will be used for objects that the demon will fight against later in onStep()
#Peer Review, Ornib - Create a timer variable to set a time period where the murderous face and sudden sound comes up

#Peer Review, Ornib - Create a global variable isAngel() that changes when you click and based on that variable, create a devil or an angel.

#Objects
ground = Rect(0,330,400,70,fill=rgb(0,154,23))
sun = Circle(-15,-15,80,fill=rgb( 249,215,28))
halo = Oval(209,133,20,5,fill=None,border='gold',borderWidth=4)
head = Circle(209,163,20,fill='white',border='pink')
neck = Line(209,163,186,200,fill='white')
torso = Line(186,200,190,221,fill='white')
leg1 = Line(190,221,227,247,fill='white')
leg1p2 = Line(227,247,225,274,fill='white')
leg2=Line(190,221,212,252,fill='white')
leg2p2 = Line(212,247,210,274,fill='white')
#Parts of the Angel that will go in the angelDevil group.

Label('Press I to open Instructions and X to Exit',200,20,fill='red',size=15)
head2 = Circle(200,185,20,fill='red',border='black',visible=False)
neck2 = Line(200,185,186,200,fill='red',visible=False)
torso2 = Line(186,200,190,221,fill='red',visible=False)
torso2p2 = Line(185,216,170,260,fill='red',lineWidth=2,visible=False)
arm = Line(190,221,227,247,fill='red', visible=False)
legDev1=Line(170,260,180,290, visible=False,fill='red',lineWidth=2)
legDev1p2 = Line(180,290,175,310,visible=False,fill='red',lineWidth=2)
legDev2  = Line(170,260,185,290,fill='red',visible=False)
legDev2p2 = Line(185,290,160,310,visible=False,fill='red')
shoe = Arc(175,310,15,3,90,180,visible=False,fill='red')
shoe2=Arc(160,310,15,3,90,180,visible=False,fill='red')
sword = Polygon(130,200,128,207,126,201,121,198,114,199,115,204,117,208,112,210,103,212,94,212,89,210, 
84,215,77,221,69,227,76,228,85,226,92,225,99,223,106,221,113,218,119,216,120,212,126,214,129,210,130,200,visible=False,fill='purple')
Coverup = Rect(0,0,400,400,fill='red',visible=False)
score = Label(app.score,375,10,fill='red',size=15,visible=False)
#Mirrored Parts of the devil without visiblity that wil go in the Devil group later
#PEER FEEDBACK BY ORNIB - ADD A SECOND SIDE TO THE ANGEL, A DEVIL



wingsForAngel = Polygon(200,193,202,187,204,181,199,175,195,170,
189,165,184,159,179,155,172,154,169,147,164,142,159,137,149,135
,142,139,136,141,124,147,114,161,107,171,104,179,99,184,94,191,88,205,
76,228,70,248,68,259,68,265,73,263,68,274,73,277,77,271,77,279,76,286,
82,283,85,278,86,289,89,296,92,291,95,284,95,289,96,294,99,301,101,294,
103,291,107,294,108,287,110,285,109,281,115,279,115,273,120,275,122,273,125,
269,129,271,136,270,141,265,141,262,146,271,151,276,155,277,158,278,164,
275,162,271,169,272,169,267,168,262,166,256,166,252,168,258,173,262,
178,266,179,261,181,257,187,255,190,250,186,246,190,242,189,238,187,229,
192,225,188,217,193,211,202,207,201,198,fill='pink', border='white')
#The Wings for the angel
wingsForDevil = Polygon(167,60,164,50,153,39,139,39,123,49,109,57,92,69,82,76,75,83,69,93,
58,103,55,116,49,133,43,161,47,190,52,216,59,252,69,276,80,303,96,328,126,373,119,357,109,
336,101,313,97,290,92,270,91,260,91,249,92,237,93,227,97,218,99,213,103,220,110,228,117,235
,122,242,117,223,
116,211,115,201,121,192,129,190,141,200,148,207,144,189,144,174,146,166,153,156,
158,151,168,149,176,150,184,161,185,149,179,136,179,127,175,129,171,136,163,132,160,122,155,112,
149,102,149,84,147,73,146,60,154,56,fill=rgb(138,3,3),border='black',borderWidth=3,visible=False)
#The Wings For The Devil

#Lists
Instructions = ['Press Any Key OTHER than I to go into manual mode','Once Manual Mode is active, you will be able to move the angel with the WASD keys', 
'Pressing mouse will switch your angel to a demon(be prepared for something ;))', 
'You can move the demon just like the angel with the WASD keys.','DO NOT click while the murderous face is active(to avoid glitches)',
'While you are in devil form and are in MANUAL mode, you will see that white circles are summoned;','those are holy objects',
'Use your sword to destroy them; move your sword with up and down','You will die if a holy object hits you in the head, torso, or leg', 'Press X to Exit']
#Instructions List() will be looped over in onKeyPress when I is pressed so that Labels are shown. The labels created by the list will then be stored in a group, Instruct

#Groups
holyObjects=Group()
Instruct = Group()
images = Group()
MurderFace = Group()
angelDevil = Group(
    halo,
    head,
    neck,
    torso,
    leg1,
    leg1p2,
    leg2,
    leg2p2,
    wingsForAngel
    )
#Peer Review, Ornib - Add a murderous face right BEFORE THE DEVIL COMES UP
# Group and Shape Methods/Properties
neck2.toFront()
torso.toBack()
arm.toBack()
torso2p2.toBack()
legDev1.toBack()
legDev1p2.toBack()
legDev2.toBack()
legDev2p2.toBack()
shoe.toBack()
shoe2.toBack()
wingsForAngel.toFront()
wingsForDevil.toFront()
sword.toFront()
score.toFront()
Coverup.toFront()

wingsForDevil.centerY+=70
#Adjusts wings to fit Devil
wingsForDevil.centerX+=10
#Adjusts wings to fit Devil
sword.centerX+=130
#Adjusts Sword
sword.centerY+=14
#Adjusts Sword
sword.width+=30
#Makes sword wider
sword.height+=30
#Makes sword taller
sword.rotateAngle+=150
#Rotates the sword to a more correct position
#Dx for Angel/Devil
angelDevil.dx=5
angelDevil.dy=5


#Peer Review, Ornib - add different wings for the DEVIL instead of just changing the Angel's wing color
#Function Area
def createWindows(x,y,color):
    #Function Creates Windows
    windowLineCenter = Line(x,y,x,y-320)
    #Local Helper Variable that creates a center Line
    windowLineCenter.toBack()
    for i in range(0,8,1):
        #For Loop Conditional 
        windowLine = Line(x-65,y-320+40*i,x+65,y-320+40*i)
        #Local Variable created inside conditional so that toBack() can be used
        windowLine.toBack()
        window1=Rect(x-65,y-320+40*i,65,40,fill=color,border='black')
        #Same Thing
        window1p2=Rect(x,y-320+40*i,65,40,fill=color,border='black')
        #Same Thing
        window1.toBack()
        window1p2.toBack()
    return windowLine,window1,window1p2,windowLineCenter
        
def createBuilding(x, y,color):
    #Function that creates buildings
    building = Rect(x, y + 10, 130, 320 - y, align='top',
        fill=color)
    #Local Variable that creates a building
    building.toBack()
    #.toBack() used to put building in the back so that the Angel appears in the front
    Line(building.centerX,building.top,building.centerX,building.top,fill='red')
    return building

def createGlassShatter(x,y):
    for i in range(8):
        #Function that creates images of shattered glass on the windows to create an illusion of reality
        for j in range(2):
            app.url='https://www.drawingnow.com/file/videos/image/how-to-draw-broken-glass-1.jpg'
            image = Image(app.url,x+65*j,y+40*i,width=65,height=40,border='red',borderWidth=5)
            images.add(image)
    return image
def summonHolyObjects():
    #This Function creates Objects that will kill the demon on impact and the demon can use his sword
    # to destroy these "holy" objects
    #These will ONLY be summoned when the DEMON is active and he is moving through USER CONTROL
    enemyX = randrange(360,399)
    enemyY = randrange(0,400)
    enemySize = randrange(6,20)
    holyObject = Circle(enemyX,enemyY,enemySize,fill=gradient('white','yellow'))
    holyObjects.add(holyObject)
    return holyObject
#Peer Review, Ornib - Make the windows on the building shatter when the devil comes

#Mouse Press Function
def onMousePress(mouseX,mouseY):
    #when the mouse is pressed, isAngel is set to either True or False, which does many things
    #First a murderous face is summoned and then a jumpscare sound is summoned
    #then the demon finally spawns and is either automatically moving or manually moving through user control
    #IF any key was pressed before the mouse press.
    #If the user is manually moving THEY Will have to destroy holy objects until they lose, there is no win
    #Life is torture. 
    if(app.isAngel==None):
        if(halo.visible==True):
            app.isAngel=True
            #app.isAngel starts off at None so this sets the starting value when the mouse is pressed
        if(halo.visible==False):
            app.isAngel=False
    
    if(app.isAngel==True):
        #when the mouse is pressed and the Angel is active, it swaps out
        #the angel body parts for the devil and sets the angel's body part's visibility to false.
        angelDevil.remove(halo,head,neck,torso,leg1,leg1p2,leg2,leg2p2)
        angelDevil.add(head2 ,neck2 ,torso2 ,arm ,wingsForDevil,torso2p2,legDev1,shoe,legDev1p2,legDev2,legDev2p2,shoe2,sword)
    
        head2.visible=True
        neck2.visible=True
        torso2.visible=True
        arm.visible=True
        torso2p2.visible=True
        legDev1.visible=True
        legDev1p2.visible=True
        legDev2.visible=True
        sword.visible=True
        legDev2p2.visible=True
        wingsForDevil.visible=True
        shoe.visible=True
        shoe2.visible=True
        score.visible=True
        
        halo.visible=False
        head.visible=False
        neck.visible=False
        torso.visible=False
        leg1.visible=False
        leg1p2.visible=False
        leg2.visible=False
        leg2p2.visible=False
        wingsForAngel.visible=False
        sun.fill=gradient(rgb(255,86,11),rgb(237,45,5),rgb(156,19,4),rgb(110,10,5),start='left')
        app.background=rgb(55,7,7)
        ground.fill='grey'
        createGlassShatter(35,10)
        createGlassShatter(235,10)
        images.visible=True
        app.isAngel=False
    elif(app.isAngel==False):
        #does the opposite of isAngel==True
        angelDevil.add(halo,head,neck,torso,leg1,leg1p2,leg2,leg2p2,wingsForAngel)
        angelDevil.remove(head2 ,neck2 ,torso2 ,arm,legDev1,legDev1p2, shoe,legDev2,legDev2p2,shoe2, wingsForDevil,sword)
        head2.visible=False
        neck2.visible=False
        torso2.visible=False
        torso2p2.visible=False
        legDev1.visible=False
        legDev2.visible=False
        legDev2p2.visible=False
        shoe.visible=False
        shoe2.visible=False
        legDev1p2.visible=False
        arm.visible=False
        wingsForDevil.visible=False
        sword.visible=False
        score.visible=False
        
        halo.visible=True
        head.visible=True
        neck.visible=True
        torso.visible=True
        leg1.visible=True
        leg1p2.visible=True
        leg2.visible=True
        leg2p2.visible=True
        wingsForAngel.visible=True
        sun.fill='yellow'
        app.background='lightBlue'
        ground.fill=rgb(0,154,23)
        images.visible=False
        app.isAngel=True
#Motion Function
def onStep():
    app.counter+=1
    #This is used as an if condition to move the holy objects
    if(app.isAngel==False and app.timer>120 and app.manualPilot==True and app.counter>=5):
        #Every 30 steps, a holy object is summoned and the app.counter variable,
        #Which is used to count the steps, gets reset to 0
        summonHolyObjects() 
        holyObjects.dx=10
        holyObjects.centerX-=holyObjects.dx
        holyObjects.toFront()
        for holyObject in holyObjects:
            if(sword.hitsShape(holyObject) or sword.containsShape(holyObject)):
                holyObjects.remove(holyObject)
                score.value+=1
                #Allows the sword to destroy holy objects
        app.counter=0
        #Resetter
        if(head2.hitsShape(holyObjects) or torso2.hitsShape(holyObjects) or legDev1.hitsShape(holyObjects)):
            app.stop()
            Label('YOU LOSE',200,200,size=50,fill='white')
            #If your head, torso, or leg hits a holy Object, you lose.
    if(app.isAngel==False):
        app.timer+=1
        #this timer Variable is used to set a time period for when the murderous face shows up and the sound plays.
        if(app.timer>1 and app.timer<100):
        #Line using AND
            app.url = 'https://i0.wp.com/creepypasta.xyz/wp-content/uploads/2017/07/Chesire-Grin.jpg'
            #Demon spawns when the timer is between 1 and 100 and a sound is also played
            image2= Image(app.url,0,0,width=400,height=400)
            MurderFace.add(image2)
            angelDevil.visible=False
            #the devil's visiblity is set to false so that no glitches occur.
            MurderFace.visible=True
            image2.visible=True
            devilSound = Sound('http://codeskulptor-demos.commondatastorage.googleapis.com/descent/Crumble%20Sound.mp3')
            # Sometimes this sound works but sometimes this doesn't even though it should work??
            #Mr Keel, Teacher Review(Not really, just listened to his advice on how to add sounds while he was talking to another person) - Sounds.
            if(app.timer<3 and app.timer>0):
                devilSound.play()
        else:
            MurderFace.visible=False
            angelDevil.visible=True
    if(app.manualPilot==False):
        angelDevil.centerX+=angelDevil.dx   
    if(angelDevil.left>492):
        #Wraparound function; allows the angel to move and wrap around.
        angelDevil.right=0
    elif(angelDevil.right<0):
        angelDevil.left=400
    return app.timer
        
def onKeyPress(key):
    if(key=='i'):
        Coverup.visible=True
        Instruct.visible=True
        i=0
        for ins in Instructions:
            insLabel = Label(ins,200,50+30*i,fill='blue',size=9)
            Instruct.add(insLabel)
            insLabel.toFront()
            i+=1
        
        angelDevil.visible=False
    elif(key=='x'):
        Coverup.visible=False
        Instruct.visible=False
        angelDevil.visible=True
    else:
        app.manualPilot=True
def onKeyHold(keys):
    if(app.manualPilot==True):
        if('w' in keys):
            angelDevil.centerY-=angelDevil.dy
        if( 's' in keys):
            angelDevil.centerY+=angelDevil.dy
        if('a' in keys):
            angelDevil.centerX-=angelDevil.dx
        if('d' in keys):
            angelDevil.centerX+=angelDevil.dx
        if('up' in keys):
            sword.rotateAngle-=10
        if('down' in keys):
            sword.rotateAngle+=10
#Function Call

createWindows(300,330,rgb(198,226,227))
createWindows(100,330,rgb(198,226,227))
createBuilding(300,0,gradient(rgb(150, 95, 90), rgb(195, 110, 115), start='center'))
createBuilding(100,0,gradient(rgb(150, 95, 90), rgb(195, 110, 115), start='center'))

